version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-workspace-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-ui-docs.rule=Host(`workspace.webdrei.com`)"
      - "traefik.http.routers.wds-ui-docs.entrypoints=websecure"
      - "traefik.http.routers.wds-ui-docs.tls.certresolver=letsencrypt"
      - traefik.http.routers.wds-ui-docs.tls=true
      - "traefik.http.services.wds-ui-docs.loadbalancer.server.port=80"
    networks:
      - app-workspace-network
      - frontend

  wds-workspace:
    image: "ghassanaldarwish/wds-workspace"
    restart: on-failure
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production

    env_file:
      - ../environment/wds-workspace/.env.local

networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
