version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-workspace-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8091:80"
    networks:
      - wds-workspace-nginx-network

  wds-workspace:
    image: "ghassanaldarwish/wds-workspace"
    restart: on-failure
    networks:
      - wds-workspace-nginx-network
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production

    env_file:
      - ../environment/wds-workspace/.env.local

networks:
  wds-workspace-nginx-network:
    name: wds-workspace-nginx-network
