---
- name: publish wds-www - production
  hosts: wds
  become: yes # Use sudo
  vars:
    destination: "/root/projects"
    project_name: "wds"
    repo_url: "git@github.com:Ghassanooooo/wds.git"
    GIT_BRANCH: main
  tasks:
    - name: Ensure that git is installed
      ansible.builtin.package:
        name: git
        state: present
    - name: Ensure directorie exist
      ansible.builtin.file:
        path: "{{ destination }}/{{ project_name }}"
        state: directory
        mode: "0755"
    - name: Check if the repository is already cloned
      ansible.builtin.stat:
        path: "{{ destination }}/{{ project_name }}/.git"
      register: git_repo

    - name: Clone the repository if not already cloned
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ destination }}/{{ project_name }}"
        version: "{{ GIT_BRANCH }}"
        accept_hostkey: yes
      when: not git_repo.stat.exists

    - name: Pull updates from the repository if it is already cloned
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ destination }}/{{ project_name }}"
        version: "{{ GIT_BRANCH }}"
        accept_hostkey: yes
        update: yes
        force: yes
      when: git_repo.stat.exists

    - name: Pull the latest images
      ansible.builtin.command:
        cmd: docker-compose -f "{{ destination }}/{{ project_name }}/production/www-wds-ui/docker-compose.wds.ui.yaml" pull
        chdir: "{{ destination }}/{{ project_name }}/production/www-wds-ui"

    - name: Run Docker Compose to start wds.ui.webdrei.com site
      ansible.builtin.command:
        cmd: docker-compose -f "{{ destination }}/{{ project_name }}/production/www-wds-ui/docker-compose.wds.ui.yaml" up -d --build
        chdir: "{{ destination }}/{{ project_name }}/production/www-wds-ui"
